import './global.css';
import { ReduxProvider } from '../store/ReduxProvider.tsx';
import { AuthenticatedLayout } from '../components/layout/AuthenticatedLayout.tsx';

export const metadata = {
  title: 'Welcome to ',
  description: 'Generated by create-nx-workspace',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="dark">
      <body className="bg-background text-foreground h-screen overflow-hidden flex flex-col">
        <ReduxProvider>
          <AuthenticatedLayout>
            {children}
          </AuthenticatedLayout>
        </ReduxProvider>
      </body>
    </html>
  );
}
