openapi: 3.0.0
info:
  title: "WRM API - Brownfield Enhancement"
  description: "API specification for the new modules: Tickets, Agent, and Collaboration."
  version: "1.0.0"
servers:
  - url: "/api"
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    # Ticket Schemas
    Ticket:
      type: object
      properties:
        id:
          type: string
          format: uuid
          description: "The unique identifier for the ticket."
        userId:
          type: string
          format: uuid
          description: "The ID of the user who owns the ticket."
        title:
          type: string
          description: "The title of the ticket."
        startTime:
          type: string
          format: date-time
          description: "The start time of the ticket."
        endTime:
          type: string
          format: date-time
          description: "The end time of the ticket."
        typeId:
          type: string
          format: uuid
          description: "The ID of the associated ticket type."
        customProperties:
          type: object
          additionalProperties: true
          description: "A JSON object for custom fields defined in the ticket type."
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time
    CreateTicketDto:
      type: object
      required:
        - title
        - startTime
        - endTime
        - typeId
      properties:
        title:
          type: string
        startTime:
          type: string
          format: date-time
        endTime:
          type: string
          format: date-time
        typeId:
          type: string
          format: uuid
        customProperties:
          type: object
          additionalProperties: true
    UpdateTicketDto:
      type: object
      properties:
        title:
          type: string
        startTime:
          type: string
          format: date-time
        endTime:
          type: string
          format: date-time
        typeId:
          type: string
          format: uuid
        customProperties:
          type: object
          additionalProperties: true

    # Authentication Schemas
    SignUpDto:
      type: object
      required:
        - email
        - password
      properties:
        email:
          type: string
          format: email
          example: "user@example.com"
          description: "User email address"
        password:
          type: string
          minLength: 6
          example: "password123"
          description: "User password (minimum 6 characters)"
        full_name:
          type: string
          example: "John Doe"
          description: "Full name"
    
    SignInDto:
      type: object
      required:
        - email
        - password
      properties:
        email:
          type: string
          format: email
          example: "user@example.com"
          description: "User email address"
        password:
          type: string
          example: "password123"
          description: "User password"
    
    RefreshTokenDto:
      type: object
      required:
        - refreshToken
      properties:
        refreshToken:
          type: string
          example: "refresh_token_here"
          description: "Refresh token"
    
    ResendConfirmationDto:
      type: object
      required:
        - email
      properties:
        email:
          type: string
          format: email
          example: "user@example.com"
          description: "User email address"
    
    AuthResponse:
      type: object
      properties:
        access_token:
          type: string
          description: "JWT access token"
        refresh_token:
          type: string
          description: "Refresh token"
        expires_in:
          type: number
          description: "Token expiration time in seconds"
        token_type:
          type: string
          example: "bearer"
        user:
          type: object
          properties:
            id:
              type: string
              format: uuid
            email:
              type: string
              format: email
            user_metadata:
              type: object
            app_metadata:
              type: object
            created_at:
              type: string
              format: date-time
            updated_at:
              type: string
              format: date-time
    
    UserProfile:
      type: object
      properties:
        user:
          type: object
          properties:
            id:
              type: string
              format: uuid
            email:
              type: string
              format: email
            user_metadata:
              type: object
            app_metadata:
              type: object
            created_at:
              type: string
              format: date-time
            updated_at:
              type: string
              format: date-time
    
    AuthError:
      type: object
      properties:
        error:
          type: string
          description: "Error message"
        statusCode:
          type: number
          description: "HTTP status code"
        message:
          type: string
          description: "Detailed error message"

    # TicketType Schemas
    TicketType:
      type: object
      properties:
        id:
          type: string
          format: uuid
        userId:
          type: string
          format: uuid
        name:
          type: string
          description: "The name of the ticket type (e.g., 'Meeting', 'Task')."
        propertiesSchema:
          type: object
          description: "A JSON schema defining the custom properties for this type."
    CreateTicketTypeDto:
      type: object
      required:
        - name
        - propertiesSchema
      properties:
        name:
          type: string
        propertiesSchema:
          type: object
    UpdateTicketTypeDto:
      type: object
      properties:
        name:
          type: string
        propertiesSchema:
          type: object

    # Agent Schemas
    AgentCommandDto:
      type: object
      required:
        - command
      properties:
        command:
          type: string
          description: "The natural language command from the user."
        context:
          type: object
          description: "Optional context, like current view or selected items."
    AgentResponseDto:
      type: object
      properties:
        message:
          type: string
          description: "A summary of the action taken by the agent."
        action:
          type: string
          description: "The type of action performed (e.g., 'CREATE_TICKET', 'UPDATE_TICKET')."
        data:
          type: object
          description: "The resulting data from the action, e.g., the created ticket."

    # Collaboration Schemas
    ShareTimelineDto:
      type: object
      required:
        - timelineId
        - recipientEmail
        - permission
      properties:
        timelineId:
          type: string
          format: uuid
        recipientEmail:
          type: string
          format: email
        permission:
          type: string
          enum: [view, edit]
    ShareDetailsDto:
      type: object
      properties:
        id:
          type: string
          format: uuid
        timelineId:
          type: string
          format: uuid
        sharedWithEmail:
          type: string
          format: email
        permission:
          type: string
          enum: [view, edit]

# Paths and Operations
paths:
  # Authentication Endpoints
  /auth/signup:
    post:
      tags: [Authentication]
      summary: "Register a new user"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SignUpDto'
      responses:
        '201':
          description: "User successfully created"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AuthResponse'
        '400':
          description: "Bad request"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AuthError'
  
  /auth/signin:
    post:
      tags: [Authentication]
      summary: "Sign in user"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SignInDto'
      responses:
        '200':
          description: "User successfully signed in"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AuthResponse'
        '401':
          description: "Invalid credentials"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AuthError'
  
  /auth/signout:
    post:
      tags: [Authentication]
      summary: "Sign out user"
      security:
        - bearerAuth: []
      responses:
        '200':
          description: "User successfully signed out"
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Successfully signed out"
        '401':
          description: "Unauthorized"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AuthError'
  
  /auth/refresh:
    post:
      tags: [Authentication]
      summary: "Refresh authentication token"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RefreshTokenDto'
      responses:
        '200':
          description: "Token successfully refreshed"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AuthResponse'
        '401':
          description: "Invalid refresh token"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AuthError'
  
  /auth/resend-confirmation:
    post:
      tags: [Authentication]
      summary: "Resend email confirmation"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ResendConfirmationDto'
      responses:
        '200':
          description: "Confirmation email resent"
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Confirmation email sent"
        '400':
          description: "Invalid email address"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AuthError'
  
  /auth/me:
    get:
      tags: [Authentication]
      summary: "Get current user profile"
      security:
        - bearerAuth: []
      responses:
        '200':
          description: "User profile retrieved successfully"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserProfile'
        '401':
          description: "Unauthorized"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AuthError'
  
  /auth/callback:
    get:
      tags: [Authentication]
      summary: "Handle email confirmation callback"
      parameters:
        - name: token_hash
          in: query
          required: true
          schema:
            type: string
          description: "Email confirmation token hash"
        - name: type
          in: query
          required: true
          schema:
            type: string
          description: "Confirmation type"
      responses:
        '302':
          description: "Redirect to success or error page"
        '400':
          description: "Invalid confirmation parameters"

  # Ticket Endpoints
  /tickets:
    get:
      tags: [Tickets]
      summary: "Get all tickets for the user"
      security:
        - bearerAuth: []
      responses:
        '200':
          description: "A list of tickets."
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Ticket'
    post:
      tags: [Tickets]
      summary: "Create a new ticket"
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateTicketDto'
      responses:
        '201':
          description: "The created ticket."
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Ticket'

  /tickets/{id}:
    get:
      tags: [Tickets]
      summary: "Get a ticket by ID"
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: "The requested ticket."
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Ticket'
    patch:
      tags: [Tickets]
      summary: "Update a ticket"
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateTicketDto'
      responses:
        '200':
          description: "The updated ticket."
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Ticket'
    delete:
      tags: [Tickets]
      summary: "Delete a ticket"
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '204':
          description: "Ticket deleted successfully."

  /ticket-types:
    get:
      tags: [TicketTypes]
      summary: "Get all ticket types for the user"
      security:
        - bearerAuth: []
      responses:
        '200':
          description: "A list of ticket types."
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/TicketType'
    post:
      tags: [TicketTypes]
      summary: "Create a new ticket type"
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateTicketTypeDto'
      responses:
        '201':
          description: "The created ticket type."
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TicketType'

  /agent/command:
    post:
      tags: [Agent]
      summary: "Send a command to the AI Agent"
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AgentCommandDto'
      responses:
        '200':
          description: "The agent's response."
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AgentResponseDto'

  /share/timeline:
    post:
      tags: [Collaboration]
      summary: "Share a timeline with another user"
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ShareTimelineDto'
      responses:
        '201':
          description: "Sharing details."
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ShareDetailsDto'